---
- name: Install kubectl
  hosts: configure-node
  become: yes

  tasks:
    - name: Install kubectl
      shell: |
        wget https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
      args:
        executable: /bin/bash

    - name: Validate kubectl Installation
      command: kubectl version --client

